version: "3.9"
services:
  vnc-browser:
    container_name: vnc-browser
    image: mrcolorrain/vnc-browser:debian
    ports:
      - "5900:5900"
      - "5900:5900"
    environment:
      VNC_PASSWORD: "1234"
    restart: unless-stopped
